---
before_install:
  - "wget https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip -O /tmp/terraform.zip"
  - "sudo unzip -d /usr/local/bin/ /tmp/terraform.zip"
dist: trusty
env:
  - tf_version=0.12.12
  - tf_version=0.12.20
language: shell
os: linux
script:
  - "make test"
  - "make fmt"